parameters:
#    vd_hackaton_violin.example.class: VDHackaton\ViolinBundle\Example

services:
#    vd_hackaton_violin.example:
#        class: %vd_hackaton_violin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
